# -*- coding: utf-8 -*-
"""practice q loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hr5Qs0JRW9zC4jTdeVzrlcaNNgxqwRIS
"""

#1.write a for loop to calculate the factorial of a number
num = int(input())
factorial = 1
for i in range(1, num + 1):
 factorial *= i
print( factorial)

#2.write a while loop that asks the user to enter a number and stops when the number is o.
while True:
 num = int(input())
 if num == 0:
  break
print(num)

#2.write a while loop that asks the user to enter a number and stops when the number is o.
a=int(input())
while a>0:
  a=int(input())

#3.write a for loop to iterate over a list of strings and print each string in uppercase.
s1=['hello','regex','an']
for i in s1:
 print(i.upper())

#4.write a while loop to reverse a number provided by the user.
a=int(input())
rev=0
while (a>0):
  b=a%10
  rev=rev*10+b
  a-=1
  a=a//10
print(rev)

#5.Provide an example where you use a for loop inside a while loop.
n=1
while n<5:
 for i in range(n):
  n+=1
  print(i)

#6.write a fibonnic sequence up to n terms,where n is provided by the user.
n=int(input())
a=0
b=1

for i in range(n):
  print(a)
  a=b
  b=a+b

#7.write a for loop that iterates over a dictionary and prints the key value pairs in the format key :value.
my_dict = {'name':'Alice', 'age': 25, 'city': 'New York'}
for key, value in my_dict.items():
 print(f'{key}: {value}')

#8.write a while loop to sum the digits of a positive integer provided by the user.
a=int(input())
sum=1
while sum<a:
   sum=sum+a%10
   a=a//10
print(sum)

#9.write a for loop to print all prime numbers between 2 and 50.
for i in range(2,51):
  for j in range(2,i):
   if i%j==0:
    break
  else:
    print(i)

#10.write a for loop to reverse a string provided by the user without using
#built-in functions.
s = input()
reversed_s = ""
for char in s:
 reversed_s = char + reversed_s
print(reversed_s)

#11.Give a list of words,write a for loop to find the longest word and its length.
words=['apple','mango','bananaedd','grapes']
longest_word=''
for word in words:
  if len(word)>len(longest_word):
    longest_word= word
print(longest_word)
print(len(longest_word))

#11.Give a list of words,write a for loop to find the longest word and its length.
a=['an','nit','vardha','kylie','tisu']
count=0
for i in a:
  count=count+1
print(count)